services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mealmate_mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong(!)Password123"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong(!)Password123' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - mealmate_net

  api:
    build:
      context: .
    container_name: mealmate_api
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=MealMateDb;User Id=sa;Password=YourStrong(!)Password123;TrustServerCertificate=True;Encrypt=False;"
    ports:
      - "8080:8080"
    networks:
      - mealmate_net

volumes:
  mssqldata:

networks:
  mealmate_net:
